# Generated by Django 4.2.11 on 2024-05-26 06:57

from django.db import migrations, models
import utils.model_util.custom_date_time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('created_at', utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True)),
                ('updated_at', utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('value', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
