# Generated by Django 4.2.11 on 2024-05-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Pass'), (2, 'Fail')], default=0)),
                ('remark', models.CharField(default='', max_length=100)),
                ('obstacle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.obstacle')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
