# Generated by Django 4.2.11 on 2024-05-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sessionreport',
            table='report_session_report',
        ),
    ]
