# Generated by Django 4.2.11 on 2024-05-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_finalreport_result_finalreport_score'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='finalreport',
            table='report_final_report',
        ),
    ]
