# Generated by Django 4.2.11 on 2024-05-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_alter_session_pid'),
        ('report', '0005_alter_finalreport_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='session',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, to='course.session'),
            preserve_default=False,
        ),
    ]
