# Generated by Django 4.2.11 on 2024-05-24 14:40

from django.db import migrations, models
import django.db.models.deletion
import utils.model_util.custom_date_time


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_delete_sensorfeed'),
        ('report', '0006_finalreport_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalreport',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SensorFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s0', models.IntegerField(blank=True, null=True)),
                ('s1', models.IntegerField(blank=True, null=True)),
                ('s2', models.IntegerField(blank=True, null=True)),
                ('s3', models.IntegerField(blank=True, null=True)),
                ('s4', models.IntegerField(blank=True, null=True)),
                ('s5', models.IntegerField(blank=True, null=True)),
                ('s6', models.IntegerField(blank=True, null=True)),
                ('s7', models.IntegerField(blank=True, null=True)),
                ('s8', models.IntegerField(blank=True, null=True)),
                ('s9', models.IntegerField(blank=True, null=True)),
                ('s10', models.IntegerField(blank=True, null=True)),
                ('s11', models.IntegerField(blank=True, null=True)),
                ('s12', models.IntegerField(blank=True, null=True)),
                ('s13', models.IntegerField(blank=True, null=True)),
                ('s14', models.IntegerField(blank=True, null=True)),
                ('s15', models.IntegerField(blank=True, null=True)),
                ('s16', models.IntegerField(blank=True, null=True)),
                ('created_at', utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True)),
                ('obstacle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='course.obstacle')),
            ],
            options={
                'db_table': 'report_sensor_feed',
            },
        ),
    ]
