# Generated by Django 4.2.11 on 2024-05-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_finalreport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalreport',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
