# Generated by Django 4.2.11 on 2024-05-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_finalreport_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalreport',
            name='score',
        ),
        migrations.AddField(
            model_name='finalreport',
            name='obtained_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='finalreport',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='finalreport',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
