# Generated by Django 4.2.11 on 2024-05-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_remove_finalreport_score_finalreport_obtained_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalreport',
            old_name='duration',
            new_name='obstacle_duration',
        ),
    ]
