# Generated by Django 4.2.11 on 2024-03-09 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorFeed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('s1', models.IntegerField(max_length=2)),
                ('s2', models.IntegerField(max_length=2)),
                ('s3', models.IntegerField(max_length=2)),
                ('s4', models.IntegerField(max_length=2)),
                ('s5', models.IntegerField(max_length=2)),
                ('s6', models.IntegerField(max_length=2)),
                ('s7', models.IntegerField(max_length=2)),
                ('s8', models.IntegerField(max_length=2)),
                ('s9', models.IntegerField(max_length=2)),
                ('s10', models.IntegerField(max_length=2)),
                ('s11', models.IntegerField(max_length=2)),
                ('s12', models.IntegerField(max_length=2)),
                ('s13', models.IntegerField(max_length=2)),
                ('s14', models.IntegerField(max_length=2)),
                ('s15', models.IntegerField(max_length=2)),
                ('s16', models.IntegerField(max_length=2)),
                ('s17', models.IntegerField(max_length=2)),
                ('s18', models.IntegerField(max_length=2)),
                ('s19', models.IntegerField(max_length=2)),
                ('device_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='ObstacleTaskScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('obstacle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.obstacle')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
