# Generated by Django 4.2.11 on 2024-03-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_id_alter_obstacle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unique_ref_id', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('type', models.IntegerField(max_length=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'unique_together': {('course_id', 'unique_ref_id')},
            },
        ),
    ]
