# Generated by Django 4.2.11 on 2024-05-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_taskmetrics_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstacletaskscore',
            name='name',
        ),
        migrations.RemoveField(
            model_name='obstacletaskscore',
            name='order',
        ),
        migrations.AlterField(
            model_name='obstacletaskscore',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
