# Generated by Django 4.2.11 on 2024-03-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course_id',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('Rect', 'Rect'), ('SEP', 'SEP'), ('L Nk', 'L Nk'), ('Nk', 'Nk'), ('L Hav', 'L Hav'), ('Hav', 'Hav'), ('Nb Sub', 'Nb Sub'), ('Sub', 'Sub'), ('Sub Maj', 'Sub Maj'), ('Lt', 'Lt'), ('Maj', 'Maj'), ('Capt', 'Capt'), ('Lt Col', 'Lt Col')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Driver'), (2, 'Instructor')], max_length=1),
        ),
    ]
