# Generated by Django 4.2.11 on 2024-05-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_obstacletaskscore_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstacletaskscore',
            name='task_id',
        ),
        migrations.AddField(
            model_name='obstacletaskscore',
            name='success_task_metrics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='course.taskmetrics'),
        ),
        migrations.AlterField(
            model_name='obstacletaskscore',
            name='obstacle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.obstacle'),
        ),
    ]
