# Generated by Django 4.2.11 on 2024-05-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_obstacletaskscore_task_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obstacle',
            old_name='track_id',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='obstacletaskscore',
            old_name='obstacle_id',
            new_name='obstacle',
        ),
        migrations.RenameField(
            model_name='taskmetrics',
            old_name='task_id',
            new_name='task',
        ),
    ]
