# Generated by Django 4.2.11 on 2024-03-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_course_id_user_course_alter_user_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorfeed',
            name='course_id',
        ),
        migrations.AddField(
            model_name='sensorfeed',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='course.course'),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='audio_file',
            field=models.FileField(upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='device_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Driver'), (2, 'Instructor')], default=1, max_length=1),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.course')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trinee_user_set', to='course.user')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainer_user_set', to='course.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sensorfeed',
            name='training',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='course.training'),
        ),
    ]
