# Generated by Django 4.2.11 on 2024-05-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_track_id_obstacle_track_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObstacleSessionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'In Progres'), (1, 'Completed')], default=0)),
                ('report_status', models.IntegerField(choices=[(0, 'In Progres'), (1, 'Completed')], default=0)),
                ('obstacle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.obstacle')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
