# Generated by Django 4.2.11 on 2024-04-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_sensorfeed_course_id_sensorfeed_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='obstacletaskscore',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='obstacletaskscore',
            name='order',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Ideal'), (1, 'In progress'), (2, 'Completed')], default=0, max_length=1)),
                ('trainee_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainee_session_set', to='course.user')),
                ('trainer_no', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trainer_session_set', to='course.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
