# Generated by Django 4.2.11 on 2024-04-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_obstacle_audio_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obstacle',
            old_name='end_device_id',
            new_name='end_rf_id',
        ),
        migrations.RenameField(
            model_name='obstacle',
            old_name='start_device_id',
            new_name='start_rf_id',
        ),
    ]
