# Generated by Django 4.2.11 on 2024-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_end_device_id_obstacle_end_rf_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ideal'), (1, 'In progress'), (2, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Driver'), (2, 'Instructor')], default=1),
        ),
    ]
