# Generated by Django 4.2.11 on 2024-05-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_obstacletaskscore_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskMetrics',
            new_name='TaskMetric',
        ),
        migrations.AlterModelTable(
            name='obstaclesessiontracker',
            table='obstacle_session_tracker',
        ),
        migrations.AlterModelTable(
            name='obstacletaskscore',
            table='obstacle_task_score',
        ),
        migrations.AlterModelTable(
            name='sensorfeed',
            table='sensor_feed',
        ),
        migrations.AlterModelTable(
            name='taskmetric',
            table='task_metric',
        ),
    ]
