# Generated by Django 4.2.11 on 2024-04-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_session_status_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorfeed',
            name='s1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s11',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s13',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s14',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s15',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s16',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s17',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s18',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s19',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s7',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s9',
            field=models.IntegerField(),
        ),
    ]
