# Generated by Django 4.2.11 on 2024-05-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_rename_taskmetrics_taskmetric_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='obstaclesessiontracker',
            table='course_obstacle_session_tracker',
        ),
        migrations.AlterModelTable(
            name='obstacletaskscore',
            table='course_obstacle_task_score',
        ),
        migrations.AlterModelTable(
            name='sensorfeed',
            table='course_sensor_feed',
        ),
        migrations.AlterModelTable(
            name='taskmetric',
            table='course_task_metric',
        ),
    ]
