# Generated by Django 4.2.11 on 2024-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_obstaclesessiontracker_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sensor_id',
            field=models.CharField(max_length=100),
        ),
    ]
