# Generated by Django 4.2.11 on 2024-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_sensorfeed_s1_alter_sensorfeed_s10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Learning'), (1, 'Test')], default=0),
        ),
    ]
