# Generated by Django 4.2.11 on 2024-04-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_session_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorfeed',
            name='course',
        ),
        migrations.RemoveField(
            model_name='sensorfeed',
            name='device_time',
        ),
        migrations.RemoveField(
            model_name='sensorfeed',
            name='training',
        ),
        migrations.AddField(
            model_name='sensorfeed',
            name='Obstacle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='course.obstacle'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(0, 'Boolean'), (1, 'Parking'), (2, 'Speed'), (3, 'Curve')], default=0),
        ),
        migrations.AddField(
            model_name='taskmetrics',
            name='message',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s10',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s11',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s12',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s13',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s14',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s15',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s16',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s17',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s18',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s19',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s2',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s3',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s4',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s5',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s6',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s7',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s8',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s9',
            field=models.CharField(max_length=1),
        ),
    ]
