# Generated by Django 4.2.11 on 2024-05-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_task_sensor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorfeed',
            old_name='s17',
            new_name='s0',
        ),
    ]
