# Generated by Django 4.2.11 on 2024-04-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_sensorfeed_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorfeed',
            name='s19',
            field=models.CharField(max_length=8),
        ),
    ]
