# Generated by Django 4.2.11 on 2024-05-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_rename_s17_sensorfeed_s0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorfeed',
            old_name='Obstacle',
            new_name='obstacle',
        ),
    ]
