# Generated by Django 4.2.11 on 2024-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_rename_obstacle_sensorfeed_obstacle'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacletaskscore',
            name='range_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='obstacletaskscore',
            name='range_2',
            field=models.IntegerField(default=0),
        ),
    ]
