# Generated by Django 4.2.11 on 2024-04-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_sensorfeed_s19'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorfeed',
            name='s18',
        ),
        migrations.RemoveField(
            model_name='sensorfeed',
            name='s19',
        ),
    ]
