# Generated by Django 4.2.11 on 2024-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_sensorfeed_s18_remove_sensorfeed_s19'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorfeed',
            name='s1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s10',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s11',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s12',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s13',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s14',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s15',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s16',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s17',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s5',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s6',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s7',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s8',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='s9',
            field=models.CharField(max_length=10),
        ),
    ]
