# Generated by Django 4.2.11 on 2024-05-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_obstacletaskscore_range_1_obstacletaskscore_range_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obstacletaskscore',
            name='range_1',
        ),
        migrations.RemoveField(
            model_name='obstacletaskscore',
            name='range_2',
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='range_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='range_2',
            field=models.IntegerField(default=0),
        ),
    ]
