# Generated by Django 4.2.11 on 2024-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_obstacletaskscore_range_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmetric',
            name='range_1',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='range_2',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='value',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
