# Generated by Django 4.2.11 on 2024-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_user_managers_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(0, 'Boolean'), (1, 'Parking'), (2, 'Speed'), (3, 'Turning')], default=0),
        ),
    ]
