# Generated by Django 4.2.11 on 2024-04-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_user_name_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='course.course'),
        ),
        migrations.AlterField(
            model_name='session',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Evaluate'), (1, 'Test')], default=0),
        ),
    ]
