# Generated by Django 4.2.11 on 2024-05-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_taskmetric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmetric',
            name='distance',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
