# Generated by Django 4.2.11 on 2024-05-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_taskmetric_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pid',
            field=models.IntegerField(default=None),
        ),
    ]
