# Generated by Django 4.2.11 on 2024-05-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_rename_range_1_taskmetric_max_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmetric',
            old_name='max_range',
            new_name='left_max_range',
        ),
        migrations.RenameField(
            model_name='taskmetric',
            old_name='min_range',
            new_name='left_min_range',
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='right_max_range',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='right_min_range',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
