# Generated by Django 4.2.11 on 2024-05-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_rename_max_range_taskmetric_left_max_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmetric',
            old_name='message',
            new_name='failure_message',
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='success_message',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(0, 'Boolean'), (1, 'Parking'), (2, 'Speed'), (3, 'Turning'), (4, 'Left Parking'), (5, 'Right Parking')], default=0),
        ),
    ]
