# Generated by Django 4.2.11 on 2024-05-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_rename_message_taskmetric_failure_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='start_rf_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
