# Generated by Django 4.2.11 on 2024-05-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_alter_obstacle_start_rf_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmetric',
            name='value',
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='failure_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='success_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='left_max_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='left_min_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='right_max_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='right_min_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
