# Generated by Django 4.2.11 on 2024-05-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_remove_taskmetric_value_taskmetric_failure_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obstacletaskscore',
            old_name='success_task_metrics',
            new_name='task_metrics',
        ),
        migrations.RemoveField(
            model_name='obstacletaskscore',
            name='task',
        ),
    ]
