# Generated by Django 4.2.11 on 2024-05-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_rename_success_task_metrics_obstacletaskscore_task_metrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obstacletaskscore',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='course.task'),
        ),
    ]
