# Generated by Django 4.2.11 on 2024-05-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_alter_session_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='serial_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
