# Generated by Django 4.2.11 on 2024-05-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_user_serial_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
    ]
