# Generated by Django 4.2.11 on 2024-05-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='trainee_no',
            new_name='trainee',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='trainer_no',
            new_name='trainer',
        ),
        migrations.AlterUniqueTogether(
            name='obstacletaskscore',
            unique_together={('obstacle', 'task')},
        ),
    ]
