# Generated by Django 4.2.11 on 2024-05-24 12:48

from django.db import migrations
import utils.model_util.custom_date_time


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_rename_trainee_no_session_trainee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='obstaclesessiontracker',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='obstaclesessiontracker',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='obstacletaskscore',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='obstacletaskscore',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sensorfeed',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskmetric',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=utils.model_util.custom_date_time.DateTimeWithoutTZField(auto_now=True),
        ),
    ]
