# Generated by Django 4.2.11 on 2024-05-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_alter_course_created_at_alter_course_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorFeed',
        ),
    ]
