# Generated by Django 4.2.11 on 2024-06-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_obstacletaskscore_ip_address_alter_session_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmetric',
            name='back_max_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmetric',
            name='back_min_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(0, 'Boolean'), (1, 'Parking'), (4, 'Left Parking'), (5, 'Right Parking'), (9, 'Reverse Parking'), (2, 'Speed'), (3, 'Turning'), (6, 'Left Turning'), (7, 'Right Turning'), (8, 'Zig-zag Turning')], default=0),
        ),
    ]
