# Generated by Django 4.2.11 on 2024-07-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_taskmetric_back_max_range_taskmetric_back_min_range_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.IntegerField(choices=[(0, 'Boolean'), (1, 'Parking'), (4, 'Left Parking'), (5, 'Right Parking'), (9, 'Reverse Parking'), (2, 'Speed'), (3, 'Turning'), (6, 'Left Turning'), (7, 'Right Turning'), (8, 'Zig-zag Turning'), (10, 'Figure of 8')], default=0),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('course', 'unique_ref_id'), name='course_unique_ref_id'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('course', 'serial_no'), name='course_serial_no'),
        ),
    ]
