# Generated by Django 4.2.11 on 2024-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_alter_user_unique_together_alter_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='negation_task_flag',
            field=models.BooleanField(default=False),
        ),
    ]
